apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redis-rb
subjects:
  - kind: ServiceAccount
    name: redis-sa
roleRef:
  kind: Role
  name: redis-role
  apiGroup: rbac.authorization.k8s.io
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: redis-role
rules:
    - apiGroups:
        - ''
      resources:
        - '*'
      verbs:
        - '*'
